console.log(4)
console.log(5)
let a = 10;
try{
    console.log(a)
}
catch{
    console.log("error")
}
console.log("komal")